[package]
name = "libvpx"
version = "0.1.0"
authors = ["Luca Barbato <lu_zero@gentoo.org>"]
license = "MIT"
description = "libvpx bindings"
repository = "https://github.com/rust-av/vpx-rs"
readme = "README.md"
keywords = ["libvpx","vp9"]

[features]
codec-trait = ["av-codec"]

[dependencies]
vpx-sys = { version = "0.1.0", path = "vpx-sys" }
av-data = { version = "0.1.0", path = "../rust-av/data" }
av-codec = { version = "0.1.0", path = "../rust-av/codec", optional = true }

[workspace]
members = ["vpx-sys"]

[[example]]
name = "encode"
path = "examples/encode.rs"

[dev-dependencies]
regex ="0.2"
