name: vpx

on: [push, pull_request]

jobs:

  linux-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install libvpx
      run: |
        sudo apt-get install libvpx-dev

    - name: Run tests
      run: |
        cargo test --workspace --all-features
        cargo test --workspace --no-default-features

    - name: Build documentation
      run: |
        cargo doc

  windows-test-gnu:

    runs-on: windows-latest

    env:
      MSYSTEM: MINGW64
      MSYS2_PATH_TYPE: inherit

    steps:
    - uses: actions/checkout@v3

    - name: Install Rust Windows gnu
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable-x86_64-pc-windows-gnu
        override: true

    - name: Install msys2 packages
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        install: mingw-w64-x86_64-pkgconf mingw-w64-x86_64-libvpx
        update: true

    - name: Run tests
      shell: msys2 {0}
      run: |
        cargo test --workspace --all-targets --all-features
        cargo test --workspace --all-targets --no-default-features
